import forms from "@tailwindcss/forms";


export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#dbc766",
        "inverse-on-surface": "#f0f0f9",
        "on-primary-fixed": "#001946",
        "primary-fixed": "#dae2ff",
        outline: "#737784",
        "inverse-primary": "#b1c5ff",
        "secondary-container": "#c1d1ff",
        "surface-bright": "#faf8ff",
        "tertiary-fixed": "#f8e37f",
        "on-primary-container": "#b0c5ff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#094cb2",
        background: "#faf8ff",
        secondary: "#4e5d86",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f3f3fc",
        "error-container": "#ffdad6",
        "tertiary-container": "#beab4e",
        tertiary: "#6d5e00",
        surface: "#faf8ff",
        "on-tertiary-fixed-variant": "#524600",
        "on-tertiary-fixed": "#211b00",
        "on-secondary-fixed-variant": "#36466d",
        "secondary-fixed": "#dae2ff",
        "surface-variant": "#e2e2eb",
        "secondary-fixed-dim": "#b6c6f4",
        "surface-container-highest": "#e2e2eb",
        "on-error-container": "#93000a",
        "outline-variant": "#c3c6d5",
        "on-error": "#ffffff",
        "on-background": "#191b22",
        "surface-tint": "#2259bf",
        "on-secondary-container": "#495981",
        "on-primary-fixed-variant": "#00419e",
        "on-surface": "#191b22",
        "inverse-surface": "#2e3037",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e7e7f1",
        "on-secondary-fixed": "#071a3f",
        primary: "#003686",
        "primary-fixed-dim": "#b1c5ff",
        "surface-container": "#ededf6",
        "surface-dim": "#d9d9e2",
        "on-surface-variant": "#434653",
        error: "#ba1a1a",
        "on-tertiary-container": "#4a3f00",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "display-sm": ["3rem", { lineHeight: "1.08" }],
        "headline-md": ["2rem", { lineHeight: "1.2" }],
        "title-md": ["1rem", { lineHeight: "1.5" }],
        "body-lg": ["1.125rem", { lineHeight: "1.65" }],
        "body-sm": ["0.875rem", { lineHeight: "1.4" }],
        "label-md": ["0.875rem", { lineHeight: "1.25" }],
        "label-sm": ["0.75rem", { lineHeight: "1.2" }],
        "label-lg": ["1rem", { lineHeight: "1.25" }],
      },
      gridTemplateColumns: {
        24: "repeat(24, minmax(0, 1fr))",
      },
    },
  },
  plugins: [forms],
};
