import forms from "@tailwindcss/forms";

const colorVar = (name) => `rgb(var(--color-${name}) / <alpha-value>)`;

export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": colorVar("tertiary-fixed-dim"),
        "inverse-on-surface": colorVar("inverse-on-surface"),
        "on-primary-fixed": colorVar("on-primary-fixed"),
        "primary-fixed": colorVar("primary-fixed"),
        outline: colorVar("outline"),
        "inverse-primary": colorVar("inverse-primary"),
        "secondary-container": colorVar("secondary-container"),
        "surface-bright": colorVar("surface-bright"),
        "tertiary-fixed": colorVar("tertiary-fixed"),
        "on-primary-container": colorVar("on-primary-container"),
        "surface-container-lowest": colorVar("surface-container-lowest"),
        "primary-container": colorVar("primary-container"),
        background: colorVar("background"),
        secondary: colorVar("secondary"),
        "on-secondary": colorVar("on-secondary"),
        "surface-container-low": colorVar("surface-container-low"),
        "error-container": colorVar("error-container"),
        "tertiary-container": colorVar("tertiary-container"),
        tertiary: colorVar("tertiary"),
        surface: colorVar("surface"),
        "on-tertiary-fixed-variant": colorVar("on-tertiary-fixed-variant"),
        "on-tertiary-fixed": colorVar("on-tertiary-fixed"),
        "on-secondary-fixed-variant": colorVar("on-secondary-fixed-variant"),
        "secondary-fixed": colorVar("secondary-fixed"),
        "surface-variant": colorVar("surface-variant"),
        "secondary-fixed-dim": colorVar("secondary-fixed-dim"),
        "surface-container-highest": colorVar("surface-container-highest"),
        "on-error-container": colorVar("on-error-container"),
        "outline-variant": colorVar("outline-variant"),
        "on-error": colorVar("on-error"),
        "on-background": colorVar("on-background"),
        "surface-tint": colorVar("surface-tint"),
        "on-secondary-container": colorVar("on-secondary-container"),
        "on-primary-fixed-variant": colorVar("on-primary-fixed-variant"),
        "on-surface": colorVar("on-surface"),
        "inverse-surface": colorVar("inverse-surface"),
        "on-tertiary": colorVar("on-tertiary"),
        "surface-container-high": colorVar("surface-container-high"),
        "on-secondary-fixed": colorVar("on-secondary-fixed"),
        primary: colorVar("primary"),
        "primary-fixed-dim": colorVar("primary-fixed-dim"),
        "surface-container": colorVar("surface-container"),
        "surface-dim": colorVar("surface-dim"),
        "on-surface-variant": colorVar("on-surface-variant"),
        error: colorVar("error"),
        "on-tertiary-container": colorVar("on-tertiary-container"),
        "on-primary": colorVar("on-primary"),
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "display-sm": ["3rem", { lineHeight: "1.08" }],
        "headline-md": ["2rem", { lineHeight: "1.2" }],
        "title-md": ["1rem", { lineHeight: "1.5" }],
        "body-lg": ["1.125rem", { lineHeight: "1.65" }],
        "body-sm": ["0.875rem", { lineHeight: "1.4" }],
        "label-md": ["0.875rem", { lineHeight: "1.25" }],
        "label-sm": ["0.75rem", { lineHeight: "1.2" }],
        "label-lg": ["1rem", { lineHeight: "1.25" }],
      },
      gridTemplateColumns: {
        24: "repeat(24, minmax(0, 1fr))",
      },
    },
  },
  plugins: [forms],
};
